#line 1 "DPD.flex.cpp"

#line 3 "DPD.flex.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 66
#define YY_END_OF_BUFFER 67
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[307] =
    {   0,
        0,    0,   67,   65,   63,   62,   65,   65,   65,   65,
       65,   65,   65,   54,   55,    9,   10,    8,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   64,   65,   65,   65,   63,   65,   61,    5,    0,
        2,    0,    3,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   57,   57,   54,    0,    0,    0,   55,    7,
        4,    6,   60,   60,   60,    0,    0,    0,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   50,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,    0,    0,    0,    0,    0,    1,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   58,   56,   60,   60,    0,    0,   43,   60,   60,
       60,   60,   60,   24,   60,   60,   60,   60,   60,   60,
       60,   53,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,    0,    1,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   57,
       60,   60,   60,   60,   60,   60,   60,   48,   60,   32,
       60,   60,   60,   52,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   31,   51,   40,
        0,    0,    0,    0,    0,   59,    0,   60,   25,   60,

       27,   60,   60,   60,   34,   60,   33,   60,   41,   60,
       60,   60,   60,   60,   60,   39,   60,   42,   60,   60,
       60,    0,    0,   60,   60,   60,   28,   60,   60,   60,
       30,   60,   38,   60,   60,   60,   60,   60,   26,   47,
        0,    0,   60,   60,   23,   60,   60,   49,   60,   60,
       60,   60,   60,   12,   60,    0,   60,   36,   60,   60,
       60,   60,   11,   60,   60,   60,    0,   35,   29,   60,
       45,   44,   19,   60,   60,   60,   60,   60,    0,   46,
       20,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   16,   60,   60,   22,   17,   18,   60,

       60,   13,   21,   14,   15,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    1,    1,    8,    9,
       10,    1,   11,   12,   13,   14,    1,   15,   16,   17,
       18,   19,   19,   20,   19,   21,   22,    1,    1,   23,
       24,   25,    6,    1,   26,   27,   28,   29,   30,   31,
       32,   32,   33,   32,   32,   34,   32,   32,   35,   36,
       32,   37,   38,   39,   40,   32,   32,   41,   32,   32,
        1,   42,    1,    1,   32,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   32,   52,   53,   54,   55,
       56,   57,   32,   58,   59,   60,   61,   62,   63,   41,
       64,   32,    1,    1,    1,    1,    1,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   67,   67,   67,   68,   67,   67,   69,
       70,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,   71,   72,   72,
       72,   72,   73,    1,    1,    1,    1,    1,   74,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[75] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,    2,    2,    2,    2,    2,
        2,    2,    1,    1,    1,    2,    2,    2,    2,    2,
        2,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    1,    2,    2,    2,    2,    2,    2,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1,    1,    1,    1,    1,    1,
        3,    3,    3,    1
    } ;

static const flex_int16_t yy_base[325] =
    {   0,
        0,   73,  425, 1444, 1444, 1444,  421,  396,  387,   68,
       75,   67,   83,  128,  104,  364,  350,  318,   56,  101,
      127,   59,  108,  133,   40,  123,  113,   95,   64,  154,
      160, 1444,  123,  154,  169,  131,  328, 1444, 1444,  323,
     1444,  174, 1444,  242,  199,  245,  256,  317,  185,  328,
      258,  337,  345,  361,  379,  397,  417,    0,  431, 1444,
     1444, 1444,   44,  391,  157,  224,  303,  240,  394,  183,
      331,  140,  350,  313,  397,  404,  425,  409,  401,  412,
      434,  430,  171,  437,  334,  444,  449,  440,  471,  475,
      468,  478,  481,  463,  490,  255,  294,  292,  285, 1444,

      553,    0,    0,    0,  537,  556,  287,  565,  618,  630,
      596,  638,    0,  518,  599,  596,  216,  419,  504,  521,
      614,  620,  626,  454,  629,  635,  632,  623,  654,  639,
      642,  528,  657,  663,  671,  674,  666,  680,  708,  677,
      688,  700,  705,  714,  711,  720,  723,  694,  262, 1444,
      782,    0,  848,    0,  761,  820,  521,  887,  789,  797,
      772,  756,  775,  800,  778,  810,  788,  813,  841,  827,
      857,  851,  854,  845,  884,  889,  875,  878,  892,  881,
      902,  895,  898,  906,  926,  921,  935,  863,  868,  910,
      976,    0,    0,    0,  528, 1444,  994,  949,  914,  930,

      917,  952,  959,  968,  956,  972,  962,  983,  979,  986,
      994, 1010, 1001,  997, 1017,  991, 1020, 1005, 1036, 1031,
     1044,    0,    0, 1024, 1050, 1055, 1014, 1060, 1047, 1040,
     1063, 1073, 1066, 1078, 1069, 1114, 1088, 1085, 1091, 1094,
        0, 1147, 1102, 1108, 1098, 1125, 1129, 1111, 1121, 1133,
     1137, 1144, 1155, 1140, 1161,    0, 1167, 1151, 1171, 1175,
     1180, 1184, 1187, 1190, 1194, 1239,    0, 1202, 1205, 1209,
     1212, 1215, 1218, 1232, 1242, 1246, 1251, 1260,    0, 1223,
     1229, 1236, 1264, 1256, 1270, 1277, 1283, 1341, 1274, 1298,
     1292, 1310, 1321, 1295, 1356, 1313, 1307, 1316, 1324, 1333,

     1327, 1330, 1336, 1344, 1347, 1444, 1429, 1432, 1434, 1437,
      261, 1440,  250,  249,  247,  238,  207,  200,  157,  154,
      153,  106,   77,   76
    } ;

static const flex_int16_t yy_def[325] =
    {   0,
      306,    1,  306,  306,  306,  306,  306,  306,  307,  308,
      306,  306,  306,  306,  306,  306,  306,  306,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  306,  306,  306,  306,  306,  310,  306,  306,  307,
      306,  308,  306,  306,  308,  308,  308,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  311,  306,  306,
      306,  306,  309,  309,  309,  306,  306,  306,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  306,  306,  306,  312,  310,  306,

      308,  313,  314,  315,  308,  308,  306,  306,  306,  306,
      306,  306,  311,  309,  309,  306,  306,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  312,  306,
      308,  316,  308,  317,  308,  306,  306,  306,  306,  306,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      308,  318,  153,  319,  306,  306,  306,  309,  309,  309,

      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  320,  321,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      322,  308,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  323,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  324,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  321,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,

      309,  309,  309,  309,  309,    0,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306
    } ;

static const flex_int16_t yy_nxt[1519] =
    {   0,
        4,    5,    6,    7,    8,    4,    9,   10,   11,    4,
        4,    4,   12,   13,   14,   15,   15,   15,   15,   15,
       15,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   25,   28,   29,   30,   31,   25,
       25,    4,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,    4,    4,    4,   32,    4,   32,
       33,   34,   35,   32,   36,   43,   48,  279,  267,   37,
       51,   52,   52,   52,   52,   52,   52,   52,   52,   49,
       50,   50,   50,   50,   50,   50,   50,   53,   53,   53,

       53,   53,   53,   53,   53,   78,   87,  256,   64,   44,
       66,   67,   68,   65,   66,   67,   68,   54,   59,   59,
       59,   59,   59,   59,   59,   59,   66,   67,   68,   66,
       67,   68,   97,   57,   66,   67,   68,   98,   45,   46,
       47,   54,   55,   55,   55,   55,   55,   55,   56,   56,
       57,   69,   86,   70,  242,  241,   71,   57,  223,   85,
       79,   72,   80,   74,   73,   66,   67,   68,   58,   75,
       83,   66,   67,   68,   57,   81,   76,   84,   66,   67,
       68,   43,   77,   66,   67,   68,  107,  122,   82,   95,
       95,   95,   95,   66,   67,   68,  108,   66,   67,   68,

       88,  222,   92,   66,   67,   68,   43,   89,  194,   93,
       66,   67,   68,   90,  115,   44,   91,   94,   95,   95,
       95,   95,   95,   95,   66,   67,   68,   66,   67,   68,
       66,   67,   68,   95,   95,   95,   95,   96,  120,  192,
       44,   66,   67,   68,   45,   46,   47,   42,  154,   42,
      153,  152,   43,   66,   67,   68,  101,  101,  101,  101,
      101,  101,  113,   43,  150,  105,  105,  105,  105,   45,
       46,   47,   53,   53,   53,   53,   53,   53,   53,   53,
       63,  102,  103,   42,   42,   42,   44,  100,  107,   42,
      116,  116,  116,  116,  150,   97,   42,   44,  108,   42,

       98,   42,  104,   42,  116,  116,  116,  116,  117,  105,
      105,  105,  105,  105,  105,   45,   46,   47,   48,  148,
      105,  105,  105,  105,  106,   41,   45,   46,   47,  107,
      100,   49,   50,   50,   50,   50,   50,   50,   50,  108,
      124,   62,  109,  109,  109,  109,  109,  109,  109,  109,
       54,   52,   52,   52,   52,   52,   52,   52,   52,   53,
       53,   53,   53,   53,   53,   53,   53,  116,  116,  116,
      116,  116,  116,   61,  110,   53,   53,   53,   53,   53,
       53,   53,   53,   66,   67,   68,  121,   60,  136,   41,
      110,  110,   54,   55,   55,   55,   55,   55,   55,   56,

       56,   66,   67,   68,   66,   67,   68,  110,   57,  123,
       54,   56,   56,   56,   56,   56,   56,   56,   56,   39,
       66,   67,   68,   38,  306,   57,   57,  111,  306,  111,
      306,  112,  112,  112,  112,  112,  112,  112,  112,  114,
      306,  306,  118,   57,   54,   59,   59,   59,   59,   59,
       59,   59,   59,  119,  126,  125,  130,  132,  306,  131,
       57,   66,   67,   68,   66,   67,   68,   66,   67,   68,
      127,   66,   67,   68,   66,   67,   68,   57,  128,   66,
       67,   68,   66,   67,   68,  129,  133,  134,  140,   66,
       67,   68,  306,  306,  137,   66,   67,   68,  135,  138,

       66,   67,   68,  139,   66,   67,   68,   66,   67,   68,
       66,   67,   68,  141,   66,   67,   68,  142,  144,   66,
       67,   68,  195,  147,   66,   67,   68,  146,  145,  195,
      196,  163,  143,   66,   67,   68,  306,  196,   66,   67,
       68,   66,   67,   68,   43,   66,   67,   68,   66,   67,
       68,   66,   67,   68,  148,  148,  148,  148,  148,  148,
       43,  306,  306,   43,  306,  164,  156,  151,  151,  151,
      151,  151,  151,  161,   66,   67,   68,  306,   44,  157,
      158,  158,  158,  158,  158,  158,  158,  306,   66,   67,
       68,   66,   67,   68,   44,  306,  306,   44,   66,   67,

       68,  155,  155,  155,  155,  155,  155,   45,   46,   47,
      112,  112,  112,  112,  112,  112,  112,  112,  306,  107,
      155,  306,  306,   45,   46,   47,   45,   46,   47,  108,
      306,  306,  109,  109,  109,  109,  109,  109,  109,  109,
      159,  162,  159,  306,  160,  160,  160,  160,  160,  160,
      160,  160,  112,  112,  112,  112,  112,  112,  112,  112,
       63,   63,   63,   63,   63,   63,  165,  166,  306,   66,
       67,   68,  167,  306,  306,  168,  306,  306,  170,  171,
      306,  173,  306,  306,   66,   67,   68,  169,  174,  306,
       66,   67,   68,   66,   67,   68,   66,   67,   68,   66,

       67,   68,   66,   67,   68,   66,   67,   68,  172,   66,
       67,   68,   66,   67,   68,  175,  176,  177,  306,  179,
      306,  306,  178,  306,   66,   67,   68,   66,   67,   68,
      183,  306,  306,   66,   67,   68,   66,   67,   68,  180,
      184,   66,   67,   68,   66,   67,   68,   66,   67,   68,
       66,   67,   68,  181,  185,  186,  182,  306,   66,   67,
       68,  306,  306,  188,   66,   67,   68,  306,   43,  190,
       66,   67,   68,  187,  189,   66,   67,   68,   66,   67,
       68,   66,   67,   68,   66,   67,   68,  306,  306,   43,
       66,   67,   68,   66,   67,   68,  191,  191,  191,  191,

      191,  191,   44,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  199,
      306,  156,  204,   44,  202,  306,   66,   67,   68,  198,
      200,   45,   46,   47,  157,  158,  158,  158,  158,  158,
      158,  158,   66,   67,   68,   66,   67,   68,   66,   67,
       68,  201,   45,   46,   47,   43,  203,  306,   66,   67,
       68,  306,  193,  193,  193,  193,  193,  193,  193,  193,
       66,   67,   68,  193,  193,  193,  193,  193,  193,  306,
       66,   67,   68,   66,   67,   68,  205,  306,  195,   44,
      193,  193,  193,  193,  193,  193,  196,   66,   67,   68,

      306,  197,  197,  197,  197,  197,  197,  197,  197,  206,
      207,   66,   67,   68,  208,   66,   67,   68,   45,   46,
       47,   66,   67,   68,   66,   67,   68,   66,   67,   68,
      209,  210,  211,   66,   67,   68,  214,  212,   66,   67,
       68,  216,  213,  306,  217,   66,   67,   68,   66,   67,
       68,   66,   67,   68,   66,   67,   68,  215,  218,   66,
       67,   68,   66,   67,   68,   66,   67,   68,   66,   67,
       68,  219,   66,   67,   68,  220,   66,   67,   68,  221,
       66,   67,   68,   43,   66,   67,   68,   66,   67,   68,
      225,   66,   67,   68,  226,  195,   66,   67,   68,  224,

       66,   67,   68,  196,  306,   66,   67,   68,  197,  197,
      197,  197,  197,  197,  197,  197,  227,   44,  229,   66,
       67,   68,   66,   67,   68,  228,   66,   67,   68,   66,
       67,   68,   66,   67,   68,  230,  306,  306,   66,   67,
       68,  235,   66,   67,   68,  231,   45,   46,   47,   66,
       67,   68,  232,   66,   67,   68,   66,   67,   68,  233,
      234,   66,   67,   68,   66,   67,   68,   66,   67,   68,
      236,   66,   67,   68,  237,   66,   67,   68,  238,  239,
       66,   67,   68,  243,   66,   67,   68,   66,   67,   68,
       66,   67,   68,  240,   66,   67,   68,  306,  306,  248,

      247,   66,   67,   68,  244,  246,   66,   67,   68,  245,
       66,   67,   68,  306,   66,   67,   68,   66,   67,   68,
       66,   67,   68,  249,  251,   66,   67,   68,  250,  306,
       66,   67,   68,   66,   67,   68,   66,   67,   68,   66,
       67,   68,  255,   66,   67,   68,  252,  254,   66,   67,
       68,  257,  306,  253,   43,   66,   67,   68,   66,   67,
       68,   66,   67,   68,   66,   67,   68,  258,   66,   67,
       68,  259,   66,   67,   68,  260,  261,  306,   66,   67,
       68,   66,   67,   68,   66,   67,   68,  265,   44,  263,
      306,   66,   67,   68,  262,   66,   67,   68,  264,   66,

       67,   68,  306,   66,   67,   68,  266,   66,   67,   68,
       66,   67,   68,  306,   66,   67,   68,   45,   46,   47,
      268,   66,   67,   68,  306,   66,   67,   68,  269,  270,
      272,   66,   67,   68,  271,  306,  306,   66,   67,   68,
      306,   66,   67,   68,  306,   66,   67,   68,  274,  273,
       66,   67,   68,  306,   66,   67,   68,   66,   67,   68,
       66,   67,   68,  306,   66,   67,   68,  275,  280,  276,
      306,  277,   66,   67,   68,   66,   67,   68,  278,   66,
       67,   68,   66,   67,   68,   66,   67,   68,   66,   67,
       68,  281,  285,   66,   67,   68,  286,  282,  283,   66,

       67,   68,   66,   67,   68,  284,   66,   67,   68,   66,
       67,   68,   66,   67,   68,  288,   66,   67,   68,  287,
      290,   66,   67,   68,  289,  291,   66,   67,   68,  298,
       66,   67,   68,  295,   66,   67,   68,  299,  306,  306,
       66,   67,   68,  305,   66,   67,   68,   66,   67,   68,
      296,  297,  304,   66,   67,   68,  292,  306,  293,  303,
      306,  294,   66,   67,   68,   66,   67,   68,   66,   67,
       68,  300,  306,  301,  306,  306,  302,   66,   67,   68,
       66,   67,   68,   66,   67,   68,   66,   67,   68,  306,
      306,   66,   67,   68,   66,   67,   68,   66,   67,   68,

       66,   67,   68,   66,   67,   68,   66,   67,   68,  306,
      306,   66,   67,   68,   66,   67,   68,   66,   67,   68,
      306,  306,  306,  306,  306,  306,   66,   67,   68,   40,
       40,   40,   42,   42,   42,   63,   63,   99,   99,   99,
      149,  149,  149,    3,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,

      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306
    } ;

static const flex_int16_t yy_chk[1519] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,   10,   11,  324,  323,    2,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   11,
       11,   11,   11,   11,   11,   11,   11,   13,   13,   13,

       13,   13,   13,   13,   13,   22,   29,  322,   19,   10,
       25,   25,   25,   19,   63,   63,   63,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   19,   19,   19,   22,
       22,   22,   36,   15,   29,   29,   29,   36,   10,   10,
       10,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       15,   20,   28,   20,  321,  320,   20,   14,  319,   27,
       23,   20,   23,   21,   20,   28,   28,   28,   14,   21,
       26,   20,   20,   20,   14,   24,   21,   26,   23,   23,
       23,   42,   21,   27,   27,   27,   49,   72,   24,   33,
       33,   33,   33,   26,   26,   26,   49,   21,   21,   21,

       30,  318,   31,   24,   24,   24,   45,   30,  317,   31,
       72,   72,   72,   30,   65,   42,   30,   31,   34,   34,
       34,   34,   34,   34,   30,   30,   30,   65,   65,   65,
       31,   31,   31,   35,   35,   35,   35,   35,   70,  316,
       45,   83,   83,   83,   42,   42,   42,   44,  315,   44,
      314,  313,   46,   70,   70,   70,   44,   44,   44,   44,
       44,   44,  311,   47,  149,   45,   45,   45,   45,   45,
       45,   45,   51,   51,   51,   51,   51,   51,   51,   51,
      117,   44,   44,   44,   44,   44,   46,   99,  107,   44,
       66,   66,   66,   66,   98,   97,   44,   47,  107,   44,

       97,   44,   44,   44,   68,   68,   68,   68,   68,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   48,   96,
       47,   47,   47,   47,   47,   40,   47,   47,   47,   50,
       37,   48,   48,   48,   48,   48,   48,   48,   48,   50,
       74,   18,   50,   50,   50,   50,   50,   50,   50,   50,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   53,
       53,   53,   53,   53,   53,   53,   53,   67,   67,   67,
       67,   67,   67,   17,   53,   54,   54,   54,   54,   54,
       54,   54,   54,   74,   74,   74,   71,   16,   85,    9,
       54,   53,   55,   55,   55,   55,   55,   55,   55,   55,

       55,   71,   71,   71,   85,   85,   85,   54,   55,   73,
       56,   56,   56,   56,   56,   56,   56,   56,   56,    8,
       73,   73,   73,    7,    3,   55,   56,   57,    0,   57,
        0,   57,   57,   57,   57,   57,   57,   57,   57,   64,
        0,    0,   69,   56,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   69,   76,   75,   78,   80,    0,   79,
       59,   64,   64,   64,   69,   69,   69,   75,   75,   75,
       77,   79,   79,   79,   76,   76,   76,   59,   77,   78,
       78,   78,   80,   80,   80,   77,   81,   82,   88,  118,
      118,  118,    0,    0,   86,   77,   77,   77,   84,   86,

       82,   82,   82,   87,   81,   81,   81,   84,   84,   84,
       88,   88,   88,   89,   86,   86,   86,   90,   91,   87,
       87,   87,  157,   94,  124,  124,  124,   93,   92,  195,
      157,  119,   90,   94,   94,   94,    0,  195,   91,   91,
       91,   89,   89,   89,  105,   90,   90,   90,   92,   92,
       92,   93,   93,   93,   95,   95,   95,   95,   95,   95,
      101,    0,    0,  106,    0,  120,  108,  101,  101,  101,
      101,  101,  101,  114,  119,  119,  119,    0,  105,  108,
      108,  108,  108,  108,  108,  108,  108,    0,  114,  114,
      114,  120,  120,  120,  101,    0,    0,  106,  132,  132,

      132,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      111,  111,  111,  111,  111,  111,  111,  111,    0,  109,
      106,    0,    0,  101,  101,  101,  106,  106,  106,  109,
        0,    0,  109,  109,  109,  109,  109,  109,  109,  109,
      110,  115,  110,    0,  110,  110,  110,  110,  110,  110,
      110,  110,  112,  112,  112,  112,  112,  112,  112,  112,
      116,  116,  116,  116,  116,  116,  121,  122,    0,  115,
      115,  115,  123,    0,    0,  125,    0,    0,  127,  128,
        0,  130,    0,    0,  121,  121,  121,  126,  131,    0,
      122,  122,  122,  128,  128,  128,  123,  123,  123,  125,

      125,  125,  127,  127,  127,  126,  126,  126,  129,  130,
      130,  130,  131,  131,  131,  133,  134,  135,    0,  137,
        0,    0,  136,    0,  129,  129,  129,  133,  133,  133,
      140,    0,    0,  134,  134,  134,  137,  137,  137,  138,
      141,  135,  135,  135,  136,  136,  136,  140,  140,  140,
      138,  138,  138,  139,  142,  143,  139,    0,  141,  141,
      141,    0,    0,  145,  148,  148,  148,    0,  155,  147,
      142,  142,  142,  144,  146,  143,  143,  143,  139,  139,
      139,  145,  145,  145,  144,  144,  144,    0,    0,  151,
      146,  146,  146,  147,  147,  147,  151,  151,  151,  151,

      151,  151,  155,  159,  159,  159,  159,  159,  159,  159,
      159,  160,  160,  160,  160,  160,  160,  160,  160,  162,
        0,  156,  167,  151,  165,    0,  162,  162,  162,  161,
      163,  155,  155,  155,  156,  156,  156,  156,  156,  156,
      156,  156,  161,  161,  161,  163,  163,  163,  165,  165,
      165,  164,  151,  151,  151,  153,  166,    0,  167,  167,
      167,    0,  153,  153,  153,  153,  153,  153,  153,  153,
      164,  164,  164,  153,  153,  153,  153,  153,  153,    0,
      166,  166,  166,  168,  168,  168,  169,    0,  158,  153,
      153,  153,  153,  153,  153,  153,  158,  170,  170,  170,

        0,  158,  158,  158,  158,  158,  158,  158,  158,  171,
      172,  169,  169,  169,  173,  174,  174,  174,  153,  153,
      153,  172,  172,  172,  173,  173,  173,  171,  171,  171,
      175,  176,  177,  188,  188,  188,  180,  178,  189,  189,
      189,  182,  179,    0,  183,  177,  177,  177,  178,  178,
      178,  180,  180,  180,  175,  175,  175,  181,  184,  176,
      176,  176,  179,  179,  179,  182,  182,  182,  183,  183,
      183,  185,  181,  181,  181,  186,  184,  184,  184,  187,
      190,  190,  190,  191,  199,  199,  199,  201,  201,  201,
      200,  186,  186,  186,  202,  197,  185,  185,  185,  198,

      200,  200,  200,  197,    0,  187,  187,  187,  197,  197,
      197,  197,  197,  197,  197,  197,  203,  191,  206,  198,
      198,  198,  202,  202,  202,  204,  205,  205,  205,  203,
      203,  203,  207,  207,  207,  208,    0,    0,  204,  204,
      204,  214,  206,  206,  206,  210,  191,  191,  191,  209,
      209,  209,  211,  208,  208,  208,  210,  210,  210,  212,
      213,  216,  216,  216,  211,  211,  211,  214,  214,  214,
      215,  213,  213,  213,  217,  218,  218,  218,  219,  220,
      212,  212,  212,  224,  227,  227,  227,  215,  215,  215,
      217,  217,  217,  221,  224,  224,  224,    0,    0,  230,

      229,  220,  220,  220,  225,  228,  219,  219,  219,  226,
      230,  230,  230,    0,  221,  221,  221,  229,  229,  229,
      225,  225,  225,  232,  235,  226,  226,  226,  234,    0,
      228,  228,  228,  231,  231,  231,  233,  233,  233,  235,
      235,  235,  238,  232,  232,  232,  236,  237,  234,  234,
      234,  243,    0,  236,  242,  238,  238,  238,  237,  237,
      237,  239,  239,  239,  240,  240,  240,  244,  245,  245,
      245,  246,  243,  243,  243,  247,  249,    0,  244,  244,
      244,  248,  248,  248,  236,  236,  236,  253,  242,  251,
        0,  249,  249,  249,  250,  246,  246,  246,  252,  247,

      247,  247,    0,  250,  250,  250,  255,  251,  251,  251,
      254,  254,  254,    0,  252,  252,  252,  242,  242,  242,
      257,  258,  258,  258,    0,  253,  253,  253,  259,  260,
      262,  255,  255,  255,  261,    0,    0,  257,  257,  257,
        0,  259,  259,  259,    0,  260,  260,  260,  265,  264,
      261,  261,  261,    0,  262,  262,  262,  263,  263,  263,
      264,  264,  264,    0,  265,  265,  265,  266,  270,  266,
        0,  266,  268,  268,  268,  269,  269,  269,  266,  270,
      270,  270,  271,  271,  271,  272,  272,  272,  273,  273,
      273,  274,  278,  280,  280,  280,  282,  275,  276,  281,

      281,  281,  274,  274,  274,  277,  282,  282,  282,  266,
      266,  266,  275,  275,  275,  284,  276,  276,  276,  283,
      286,  277,  277,  277,  285,  287,  284,  284,  284,  292,
      278,  278,  278,  289,  283,  283,  283,  293,    0,    0,
      285,  285,  285,  301,  289,  289,  289,  286,  286,  286,
      290,  291,  300,  287,  287,  287,  288,    0,  288,  296,
        0,  288,  291,  291,  291,  294,  294,  294,  290,  290,
      290,  295,    0,  295,    0,    0,  295,  297,  297,  297,
      292,  292,  292,  296,  296,  296,  298,  298,  298,    0,
        0,  293,  293,  293,  299,  299,  299,  301,  301,  301,

      302,  302,  302,  300,  300,  300,  303,  303,  303,    0,
        0,  288,  288,  288,  304,  304,  304,  305,  305,  305,
        0,    0,    0,    0,    0,    0,  295,  295,  295,  307,
      307,  307,  308,  308,  308,  309,  309,  310,  310,  310,
      312,  312,  312,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,

      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[67] =
    {   0,
1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 1, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "DPD.l"
#line 10 "DPD.l"
#include "stdafx.h"
#include "dpd.h"
#include "DPD.tab.h"

int yycolumn = 1;
int utf8len = 0;

#define YY_USER_ACTION utf8len = GetUtf8Length(yytext, yyleng); yylloc.first_line = yylloc.last_line = yylineno; \
	yylloc.first_column = yycolumn; yylloc.last_column = yycolumn + utf8len - 1; \
	yycolumn += utf8len;
#line 924 "DPD.flex.cpp"
#line 925 "DPD.flex.cpp"

#define INITIAL 0

/*windows compatibility case*/
#include <io.h>
#define isatty _isatty
#define fileno _fileno
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 21 "DPD.l"



#line 25 "DPD.l"
	extern int first_tok;

	if(first_tok!=0) {
		int holdtok = first_tok;
		first_tok = 0;
		return holdtok;
	}


#line 1156 "DPD.flex.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 307 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1444 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 34 "DPD.l"
{ yycolumn = 1; yylval.symbol = SaveSymbol(yytext, yylloc.first_line, yylloc.first_column, yylloc.last_column); return COMMENT; }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 35 "DPD.l"
{ yycolumn = 1; }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 38 "DPD.l"
{ yylval.symbol = SaveSymbol(yytext, yylloc.first_line, yylloc.first_column, yylloc.last_column); return VALUE_STRING; }
	YY_BREAK
case 4:
#line 41 "DPD.l"
case 5:
#line 42 "DPD.l"
case 6:
#line 43 "DPD.l"
case 7:
#line 44 "DPD.l"
case 8:
#line 45 "DPD.l"
case 9:
YY_RULE_SETUP
#line 45 "DPD.l"
{ yylval.symbol = SaveSymbol(yytext, yylloc.first_line, yylloc.first_column, yylloc.last_column); return CMP; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 46 "DPD.l"
{ return EQUAL; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 48 "DPD.l"
{ return PROTOCOL; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 49 "DPD.l"
{ return SEGMENT; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 52 "DPD.l"
{ return SEGMENT_TYPE_U8; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 53 "DPD.l"
{ return SEGMENT_TYPE_U16; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 54 "DPD.l"
{ return SEGMENT_TYPE_U32; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 55 "DPD.l"
{ return SEGMENT_TYPE_I8; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 56 "DPD.l"
{ return SEGMENT_TYPE_I16; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 57 "DPD.l"
{ return SEGMENT_TYPE_I32; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 58 "DPD.l"
{ return SEGMENT_TYPE_IR; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 59 "DPD.l"
{ return SEGMENT_TYPE_UR; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 60 "DPD.l"
{ return SEGMENT_TYPE_DOUBLE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 61 "DPD.l"
{ return SEGMENT_TYPE_FLOAT; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 62 "DPD.l"
{ return SEGMENT_TYPE_BOOLEAN; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 63 "DPD.l"
{ return SEGMENT_TYPE_CRC; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 64 "DPD.l"
{ return SEGMENT_TYPE_ARRAY; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 65 "DPD.l"
{ return SEGMENT_TYPE_STRING; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 66 "DPD.l"
{ return SEGMENT_TYPE_BLOCK; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 67 "DPD.l"
{ return SEGMENT_TYPE_BUFFER; }
	YY_BREAK
case 29:
#line 70 "DPD.l"
case 30:
#line 71 "DPD.l"
case 31:
#line 72 "DPD.l"
case 32:
#line 73 "DPD.l"
case 33:
#line 74 "DPD.l"
case 34:
#line 75 "DPD.l"
case 35:
#line 76 "DPD.l"
case 36:
#line 77 "DPD.l"
case 37:
#line 78 "DPD.l"
case 38:
#line 79 "DPD.l"
case 39:
YY_RULE_SETUP
#line 79 "DPD.l"
{ yylval.symbol = SaveSymbol(yytext, yylloc.first_line, yylloc.first_column, yylloc.last_column); return SEGMENT_PROPERTY; }
	YY_BREAK
case 40:
#line 82 "DPD.l"
case 41:
YY_RULE_SETUP
#line 82 "DPD.l"
{ yylval.symbol = SaveSymbol(yytext, yylloc.first_line, yylloc.first_column, yylloc.last_column); return VALUE_BOOL; }
	YY_BREAK
case 42:
#line 85 "DPD.l"
case 43:
#line 86 "DPD.l"
case 44:
#line 87 "DPD.l"
case 45:
#line 88 "DPD.l"
case 46:
YY_RULE_SETUP
#line 88 "DPD.l"
{ yylval.symbol = SaveSymbol(yytext, yylloc.first_line, yylloc.first_column, yylloc.last_column); return VALUE_PROPERTY; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 92 "DPD.l"
{ yylval.symbol = SaveSymbol(yytext, yylloc.first_line, yylloc.first_column, yylloc.last_column); return SWITCH; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 93 "DPD.l"
{ yylval.symbol = SaveSymbol(yytext, yylloc.first_line, yylloc.first_column, yylloc.last_column); return CASE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 94 "DPD.l"
{ yylval.symbol = SaveSymbol(yytext, yylloc.first_line, yylloc.first_column, yylloc.last_column); return DEFAULT; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 95 "DPD.l"
{ yylval.symbol = SaveSymbol(yytext, yylloc.first_line, yylloc.first_column, yylloc.last_column); return IF; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 96 "DPD.l"
{ yylval.symbol = SaveSymbol(yytext, yylloc.first_line, yylloc.first_column, yylloc.last_column); return THEN; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 97 "DPD.l"
{ yylval.symbol = SaveSymbol(yytext, yylloc.first_line, yylloc.first_column, yylloc.last_column); return ELSE; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 99 "DPD.l"
{ return END; }
	YY_BREAK
case 54:
#line 102 "DPD.l"
case 55:
#line 103 "DPD.l"
case 56:
YY_RULE_SETUP
#line 103 "DPD.l"
{ yylval.symbol = SaveSymbol(yytext, yylloc.first_line, yylloc.first_column, yylloc.last_column); return VALUE_INT; }
	YY_BREAK
case 57:
#line 106 "DPD.l"
case 58:
YY_RULE_SETUP
#line 106 "DPD.l"
{ yylval.symbol = SaveSymbol(yytext, yylloc.first_line, yylloc.first_column, yylloc.last_column); return VALUE_FLOAT; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 108 "DPD.l"
{ yylval.symbol = SaveSymbol(yytext, yylloc.first_line, yylloc.first_column, yylloc.last_column); return VALUE_RANGE; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 110 "DPD.l"
{ yylval.symbol = SaveSymbol(yytext, yylloc.first_line, yylloc.first_column, yylloc.last_column); return IDENTIFIER; }
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 112 "DPD.l"
{ yycolumn=1; }
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 113 "DPD.l"
{ yycolumn=1; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 114 "DPD.l"
{ ; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 116 "DPD.l"
{ yycolumn=1; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 117 "DPD.l"
{ return ENDALL; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 118 "DPD.l"
{ OutError(ERROR_CODE_SYMBOL, yylineno, yytext); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 119 "DPD.l"
ECHO;
	YY_BREAK
#line 1494 "DPD.flex.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 307 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 307 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 306);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 119 "DPD.l"


